#!/bin/bash

if [ ! -f /routes/run.sh ];then

    echo "### Script file for routes #####" > /routes/run.sh
    echo "#ip route add 192.168.1.0/24 via 192.168.150.100" >> /routes/run.sh
fi

chmod +x /routes/run.sh
/routes/run.sh

exec pptpd -f 